=== thebestofal/xml_projekt/zoo.dtd
<?xml encoding="UTF-8"?>

<!ENTITY % dane_personalne "imię, nazwisko, pesel, telefon">
<!ELEMENT zoo (title,zwierzęta,opiekunowie,jedzenie)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT zwierzęta (zwierzę)+>

<!ELEMENT opiekunowie (opiekun)+>
<!ELEMENT opiekun (%dane_personalne;)>
<!ATTLIST opiekun id_o ID #REQUIRED>

<!ELEMENT sekcja (#PCDATA)>
<!ELEMENT zwierzę (id,gatunek,imię,wiek,waga,(wzrost|długość),sekcja,pożywienie)>
<!ATTLIST zwierzę
  xmlns CDATA #FIXED ''
  gromada NMTOKEN #REQUIRED
  idOpiekuna CDATA #IMPLIED>

<!ATTLIST wiek jednostka CDATA #REQUIRED>
<!ATTLIST waga jednostka CDATA #REQUIRED>
<!ATTLIST wzrost jednostka CDATA #REQUIRED>
<!ATTLIST długość jednostka CDATA #REQUIRED>

<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT gatunek (#PCDATA)>
<!ELEMENT wiek (#PCDATA)>
<!ELEMENT waga (#PCDATA)>
<!ELEMENT pesel (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT długość (#PCDATA)>
<!ELEMENT wzrost (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT imię (#PCDATA)>
<!ELEMENT pożywienie (produkt)*>
<!ELEMENT produkt (#PCDATA)>
<!ELEMENT jedzenie (produkty)*>

<!ELEMENT produkty (nazwa, ilość)>
<!ATTLIST produkty id_p ID #REQUIRED> 

<!ELEMENT ilość (#PCDATA)>
<!ELEMENT nazwa (#PCDATA)>
<!ATTLIST ilość jednostka CDATA #REQUIRED>

=== thebestofal/xml_projekt/zoo.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="zoo.css"?>
<!DOCTYPE zoo SYSTEM "zoo.dtd">
<zoo>
	<title>Zoo - Ewidencja zwierząt</title>
	<zwierzęta>
		<zwierzę id="_01" idOpiekuna="_11"> <!--<zwierzę id="_01" idOpiekuna="_110" -->
			<gromada>ssak</gromada>
			<gatunek>Alpaka</gatunek>
			<imię>Zosia</imię>
			<wiek jednostka="lata">4</wiek>
			<waga jednostka="kg">50</waga>
			<wzrost jednostka="cm">80</wzrost>
			<sekcja>pastwisko</sekcja>
			<pożywienie>
				<produkt>siano</produkt>
			</pożywienie>
		</zwierzę>
		<zwierzę id="_02" idOpiekuna="_12">
			<gromada>ssak</gromada>
			<gatunek>Fenek</gatunek>
			<imię>Rudy</imię>
			<wiek jednostka="lata">2</wiek>
			<waga jednostka="g">500</waga>
			<wzrost jednostka="cm">20</wzrost>
			<sekcja>drapieżniki</sekcja>
			<pożywienie>
				<produkt>jaja</produkt>
				<produkt>chrząszcze</produkt>
			</pożywienie>
		</zwierzę>
		<zwierzę id="_03" idOpiekuna="_13">
			<gromada>ptak</gromada>
			<gatunek>Nandu</gatunek>
			<imię>Nielotek</imię>
			<wiek jednostka="lata">3</wiek>
			<waga jednostka="kg">20</waga>
			<wzrost jednostka="m">1</wzrost>
			<sekcja>safari</sekcja>
			<pożywienie>
				<produkt>mieszanka dla ptaków</produkt>
			</pożywienie>
		</zwierzę>
		<zwierzę id="_04" idOpiekuna="_13">
			<gromada>ssak</gromada>
			<gatunek>Słoń afrykański</gatunek>
			<imię>Zosia</imię>
			<wiek jednostka="lata">50</wiek>
			<waga jednostka="t">6</waga>
			<wzrost jednostka="m">3</wzrost>
			<sekcja>safari</sekcja>
			<pożywienie>
				<produkt>siano</produkt>
				<produkt>owoce</produkt>
			</pożywienie>
		</zwierzę>
		<zwierzę id="_05" idOpiekuna="_14">
			<gromada>gad</gromada>
			<gatunek>Krokodyl nilowy</gatunek>
			<imię>Croco</imię>
			<wiek jednostka="lata">9</wiek>
			<waga jednostka="kg">500</waga>
			<długość jednostka="m">3</długość>
			<sekcja>safari</sekcja>
			<pożywienie>
				<produkt>ryby</produkt>
			</pożywienie>
		</zwierzę>
		<zwierzę id="_06" idOpiekuna="_14">
			<gromada>płaz</gromada>
			<gatunek>Rzekotka szmaragdowa</gatunek>
			<imię>Gąbka</imię>
			<wiek jednostka="lata">10</wiek>
			<waga jednostka="g">200</waga>
			<długość jednostka="cm">11</długość>
			<sekcja>terraria</sekcja>
			<pożywienie>
				<produkt>owady</produkt>
			</pożywienie>
		</zwierzę>
	</zwierzęta>

	<opiekunowie>
		<opiekun id_o="_11">
			<imię>Marcin</imię>
			<nazwisko>Kolec</nazwisko>
			<pesel>78040289819</pesel>
			<telefon>555666777</telefon>
		</opiekun>
		<opiekun id_o="_12">
			<imię>Aurelia</imię>
			<nazwisko>Stokowiec</nazwisko>
			<pesel>92102850526</pesel>
			<telefon>222333555</telefon>
		</opiekun>
		<opiekun id_o="_13">
			<imię>Wanda</imię>
			<nazwisko>Kędzierska</nazwisko>
			<pesel>91052705845</pesel>
			<telefon>356558788</telefon>
		</opiekun>
		<opiekun id_o="_14">
			<imię>Angelika</imię>
			<nazwisko>Kankowska</nazwisko>
			<pesel>87050773375</pesel>
			<telefon>797855412</telefon>
		</opiekun>
	</opiekunowie>

	<jedzenie>
		<produkty id_p="_1">
			<nazwa>siano</nazwa>
			<ilość jednostka="t">5</ilość>
		</produkty>
		<produkty id_p="_2">
			<nazwa>chrząszcze</nazwa>
			<ilość jednostka="kg">10</ilość>
		</produkty>
		<produkty id_p="_3">
			<nazwa>jaja</nazwa>
			<ilość jednostka="szt">500</ilość>
		</produkty>
		<produkty id_p="_4">
			<nazwa>mieszanka dla ptaków</nazwa>
			<ilość jednostka="kg">200</ilość>
		</produkty>
		<produkty id_p="_5">
			<nazwa>owoce</nazwa>
			<ilość jednostka="kg">100</ilość>
		</produkty>
		<produkty id_p="_6">
			<nazwa>ryby</nazwa>
			<ilość jednostka="szt">50</ilość>
		</produkty>
		<produkty id_p="_7">
			<nazwa>owady</nazwa>
			<ilość jednostka="kg">50</ilość>
		</produkty>
	</jedzenie>
</zoo>
